name: flutter_shuttletracker
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  device_preview: ^0.4.7
  flushbar: ^1.10.4
  flutter_cupertino_settings: ^0.3.0
  scrollable_positioned_list: ^0.1.6
  hydrated_bloc: ^6.0.0
  shared_preferences: ^0.5.7
  flutter_native_splash: ^0.1.9
  flutter_platform_widgets: ^0.41.0
  flutter_widget_from_html: ^0.3.3
  observable: ^0.22.2
  flutter_svg: ^0.17.4
  flutter_bloc: ^6.0.0
  equatable: ^1.2.0
  responsive_framework: ^0.0.7
  http: ^0.12.1
  flutter_map: ^0.10.1
  geolocation: ^1.1.2
  loading: ^1.0.2
  web_socket_channel: ^1.1.0

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_launcher_icons: "^0.7.5"
  effective_dart: ^1.2.1
  pedantic: ^1.9.0
  # flutter_test:
  #   sdk: flutter

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/img/app_icon.png"

flutter_native_splash:
  image: "assets/img/logo.png"
  color: "ffffff"


flutter:

  uses-material-design: true

  assets:
    - assets/img/student_union.jpg
    - assets/img/logo.png
    - assets/img/circle.png
    - assets/img/stop.png
    - assets/img/shuttle.svg
    - assets/img/stop_thin.png
    - assets/img/dark_stop.png
    - assets/img/user.png
    - assets/json_test/routes.json
    - assets/json_test/stops.json
    - assets/json_test/updates.json
  
  fonts:
    - family: CustomIcons
      fonts:
          - asset: assets/fonts/shuttle_icon.ttf